name: check-commit

on:
    - workflow_call

jobs:
    check-commit:
        name: Commit

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

              with:
                  fetch-depth: 0

            - uses: actions/cache@v4

              with:
                  key: ${{ github.job }}-${{ hashFiles('package-lock.json') }}

                  path: node_modules/

            - uses: actions/setup-node@v4

              with:
                  node-version: 19

            - name: Install dependencies

              run: npm install

            - name: Check commit

              run: npx commitlint --from=HEAD~1 --to HEAD --verbose
